[package]
name = "math-parser"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
symengine-rs = { workspace = true }
antlr-rust = { workspace = true }
ctor = "0.4.1"
env_logger = "0.11.8"
log = { workspace = true }
regex = "1.11.1"
test-log = { workspace = true }

[lib]
crate-type = ["rlib"]  # or ["cdylib"] for Rust-specific linkage

[dev-dependencies]
symengine-rs = { workspace = true }
env_logger = "0.11.8"
