[package]
name = "interpreter"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
log = { workspace = true }
test-log = { workspace = true }
serde = { workspace = true }
math-parser = { path = "../math-parser" }
symengine-rs = { workspace = true }
giac-rs = { workspace = true }
antlr-rust = { workspace = true }
math-core = { workspace = true }

[dev-dependencies]
